# Generated by Django 2.0.2 on 2018-05-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=20, unique=True)),
                ('go_term', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MutualInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('dataset', models.CharField(max_length=1000)),
                ('gene1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene1', to='plots.Gene')),
                ('gene2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene2', to='plots.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('dataset', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='expression',
            name='gene_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.Gene'),
        ),
        migrations.AddField(
            model_name='expression',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.Sample'),
        ),
    ]
