# Generated by Django 2.0.2 on 2018-05-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expression',
            old_name='gene_id',
            new_name='gene',
        ),
        migrations.RenameField(
            model_name='expression',
            old_name='sample_id',
            new_name='sample',
        ),
        migrations.RenameField(
            model_name='mutualinformation',
            old_name='gene1_id',
            new_name='gene1',
        ),
        migrations.RenameField(
            model_name='mutualinformation',
            old_name='gene2_id',
            new_name='gene2',
        ),
    ]
